const routes = {
  SIGN_IN: 'signin',
  OTP: 'otp',
  HOME: 'home',
  CAT_PROFILE: 'cat_profile',
  EDIT_CAT_PROFILE: 'edit_cat_profile',
  NOTIFICATIIONS: 'notifications',
  DRAWER: 'drawer',
  BOTTOM_NAVIGATION: 'bottom-navigation',
  BLOG: 'blog',
  CART: 'cart',
  LESSONS: 'lessons',
  TRICKS: 'tricks',
  CAT_NAME: 'cat_name',
  CAT_AVATAR: 'cat_avatar',
  CAT_BREED: 'cat_breed',
  CAT_DOB: 'cat_dob',
  CAT_GENDER: 'cat_gender',
  PRIVACY_POLICY: 'privacy_policy',
  TERMS_CONDITIONS: 'terms_conditions',
  WEBSITE_LINK: 'web_link',
  FEEDBACK: 'feedback',
  REWARDS: 'rewards',
};

export default routes;
